# -*- diding_ utf-8 -*-
# Generated by Django 4.1.6 on 2023-04-25 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tapahtuma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('päivä', models.DateField(help_text='Tapahtumapäivä',verbose_name='Tapahtuman päivä' )),
                ('aloitus_aika', models.TextField(help_text='Aloitus aika', verbose_name='Aloitus aika')),
                ('lopetus_aika', models.TimeField(help_text='Lopetus aika', verbose_name= 'Lopetus aika')),
                ('lisätietoja', models.TextField(blank=True, help_text='Lisätietoja', null=True, verbose_name='Textual Notes')),
            ],
            options={
                'verbose_name' : 'Scheduling',
                'verbose_name_plural' : 'Schedulin',
            }

        ),
    ]
