# -*- diding_ utf-8 -*-
# Generated by Django 4.1.6 on 2023-04-25 09:45
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    

    operations = [
        migrations.CreateModel(
            name='Tapahtuma',
            fields=[
                (
                    "id"
                    models.AutoField(
                    auto_created=True
        
                    )
            options={
                'verbose_name' : 'ID'
                'verbose_name_plural' : 'Schedulin',
            }

        ),
    ]
