# Generated by Django 4.1.6 on 2023-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalenteri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tapahtuma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsikko', models.CharField(max_length=150)),
                ('lisätieto', models.TextField(max_length=250)),
                ('aloitusaika', models.DateTimeField()),
                ('lopetusaika', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ohjelmasi',
        ),
    ]
